---
- name: Setup private and public keys
  copy:
    src: '{{ item }}'
    dest: /home/kamuri/.ssh/
    owner: kamuri
    mode: '600'
  with_fileglob:
    - "/home/kamuri/.ssh/*"

- name: Add GPG key
  shell: curl https://keybase.io/kamuridesu/pgp_keys.asc | gpg --import